export type CommandSpec = { name: string; syntax: string };

// A curated set of commonly used Redis commands with short syntax hints,
// used to power autocomplete in the query console. Not exhaustive.
export const REDIS_COMMANDS: CommandSpec[] = [
  // Generic / key management
  { name: "DEL", syntax: "DEL key [key ...]" },
  { name: "UNLINK", syntax: "UNLINK key [key ...]" },
  { name: "EXISTS", syntax: "EXISTS key [key ...]" },
  { name: "EXPIRE", syntax: "EXPIRE key seconds [NX|XX|GT|LT]" },
  { name: "PEXPIRE", syntax: "PEXPIRE key milliseconds [NX|XX|GT|LT]" },
  { name: "EXPIREAT", syntax: "EXPIREAT key unix-time-seconds" },
  { name: "PEXPIREAT", syntax: "PEXPIREAT key unix-time-milliseconds" },
  { name: "EXPIRETIME", syntax: "EXPIRETIME key" },
  { name: "PEXPIRETIME", syntax: "PEXPIRETIME key" },
  { name: "PERSIST", syntax: "PERSIST key" },
  { name: "TTL", syntax: "TTL key" },
  { name: "PTTL", syntax: "PTTL key" },
  { name: "TYPE", syntax: "TYPE key" },
  { name: "RENAME", syntax: "RENAME key newkey" },
  { name: "RENAMENX", syntax: "RENAMENX key newkey" },
  { name: "COPY", syntax: "COPY source destination [DB destination-db] [REPLACE]" },
  { name: "MOVE", syntax: "MOVE key db" },
  { name: "KEYS", syntax: "KEYS pattern" },
  { name: "SCAN", syntax: "SCAN cursor [MATCH pattern] [COUNT count] [TYPE type]" },
  { name: "RANDOMKEY", syntax: "RANDOMKEY" },
  { name: "DBSIZE", syntax: "DBSIZE" },
  { name: "DUMP", syntax: "DUMP key" },
  { name: "RESTORE", syntax: "RESTORE key ttl serialized-value [REPLACE]" },
  { name: "TOUCH", syntax: "TOUCH key [key ...]" },
  { name: "OBJECT", syntax: "OBJECT subcommand [arguments]" },
  { name: "SORT", syntax: "SORT key [BY pattern] [LIMIT offset count] [GET pattern] [ASC|DESC] [ALPHA]" },
  { name: "SORT_RO", syntax: "SORT_RO key [BY pattern] [LIMIT offset count] [GET pattern]" },
  { name: "WAIT", syntax: "WAIT numreplicas timeout" },

  // Strings
  { name: "GET", syntax: "GET key" },
  { name: "SET", syntax: "SET key value [EX seconds|PX ms|EXAT ts|PXAT ts|KEEPTTL] [NX|XX] [GET]" },
  { name: "GETSET", syntax: "GETSET key value" },
  { name: "GETDEL", syntax: "GETDEL key" },
  { name: "GETEX", syntax: "GETEX key [EX seconds|PX ms|EXAT ts|PXAT ts|PERSIST]" },
  { name: "SETNX", syntax: "SETNX key value" },
  { name: "SETEX", syntax: "SETEX key seconds value" },
  { name: "PSETEX", syntax: "PSETEX key milliseconds value" },
  { name: "MGET", syntax: "MGET key [key ...]" },
  { name: "MSET", syntax: "MSET key value [key value ...]" },
  { name: "MSETNX", syntax: "MSETNX key value [key value ...]" },
  { name: "APPEND", syntax: "APPEND key value" },
  { name: "STRLEN", syntax: "STRLEN key" },
  { name: "GETRANGE", syntax: "GETRANGE key start end" },
  { name: "SETRANGE", syntax: "SETRANGE key offset value" },
  { name: "INCR", syntax: "INCR key" },
  { name: "INCRBY", syntax: "INCRBY key increment" },
  { name: "INCRBYFLOAT", syntax: "INCRBYFLOAT key increment" },
  { name: "DECR", syntax: "DECR key" },
  { name: "DECRBY", syntax: "DECRBY key decrement" },

  // Bitmaps
  { name: "SETBIT", syntax: "SETBIT key offset value" },
  { name: "GETBIT", syntax: "GETBIT key offset" },
  { name: "BITCOUNT", syntax: "BITCOUNT key [start end [BYTE|BIT]]" },
  { name: "BITPOS", syntax: "BITPOS key bit [start [end [BYTE|BIT]]]" },
  { name: "BITOP", syntax: "BITOP operation destkey key [key ...]" },
  { name: "BITFIELD", syntax: "BITFIELD key [GET|SET|INCRBY|OVERFLOW ...]" },

  // Hashes
  { name: "HSET", syntax: "HSET key field value [field value ...]" },
  { name: "HSETNX", syntax: "HSETNX key field value" },
  { name: "HGET", syntax: "HGET key field" },
  { name: "HMSET", syntax: "HMSET key field value [field value ...]" },
  { name: "HMGET", syntax: "HMGET key field [field ...]" },
  { name: "HGETALL", syntax: "HGETALL key" },
  { name: "HDEL", syntax: "HDEL key field [field ...]" },
  { name: "HEXISTS", syntax: "HEXISTS key field" },
  { name: "HLEN", syntax: "HLEN key" },
  { name: "HKEYS", syntax: "HKEYS key" },
  { name: "HVALS", syntax: "HVALS key" },
  { name: "HSTRLEN", syntax: "HSTRLEN key field" },
  { name: "HINCRBY", syntax: "HINCRBY key field increment" },
  { name: "HINCRBYFLOAT", syntax: "HINCRBYFLOAT key field increment" },
  { name: "HRANDFIELD", syntax: "HRANDFIELD key [count [WITHVALUES]]" },
  { name: "HSCAN", syntax: "HSCAN key cursor [MATCH pattern] [COUNT count] [NOVALUES]" },
  { name: "HEXPIRE", syntax: "HEXPIRE key seconds FIELDS numfields field [field ...]" },
  { name: "HTTL", syntax: "HTTL key FIELDS numfields field [field ...]" },
  { name: "HPERSIST", syntax: "HPERSIST key FIELDS numfields field [field ...]" },

  // Lists
  { name: "LPUSH", syntax: "LPUSH key element [element ...]" },
  { name: "RPUSH", syntax: "RPUSH key element [element ...]" },
  { name: "LPUSHX", syntax: "LPUSHX key element [element ...]" },
  { name: "RPUSHX", syntax: "RPUSHX key element [element ...]" },
  { name: "LPOP", syntax: "LPOP key [count]" },
  { name: "RPOP", syntax: "RPOP key [count]" },
  { name: "LLEN", syntax: "LLEN key" },
  { name: "LRANGE", syntax: "LRANGE key start stop" },
  { name: "LINDEX", syntax: "LINDEX key index" },
  { name: "LSET", syntax: "LSET key index element" },
  { name: "LINSERT", syntax: "LINSERT key BEFORE|AFTER pivot element" },
  { name: "LREM", syntax: "LREM key count element" },
  { name: "LTRIM", syntax: "LTRIM key start stop" },
  { name: "LPOS", syntax: "LPOS key element [RANK rank] [COUNT count]" },
  { name: "LMOVE", syntax: "LMOVE source destination LEFT|RIGHT LEFT|RIGHT" },
  { name: "RPOPLPUSH", syntax: "RPOPLPUSH source destination" },
  { name: "BLPOP", syntax: "BLPOP key [key ...] timeout" },
  { name: "BRPOP", syntax: "BRPOP key [key ...] timeout" },
  { name: "BLMOVE", syntax: "BLMOVE source destination LEFT|RIGHT LEFT|RIGHT timeout" },

  // Sets
  { name: "SADD", syntax: "SADD key member [member ...]" },
  { name: "SREM", syntax: "SREM key member [member ...]" },
  { name: "SMEMBERS", syntax: "SMEMBERS key" },
  { name: "SISMEMBER", syntax: "SISMEMBER key member" },
  { name: "SMISMEMBER", syntax: "SMISMEMBER key member [member ...]" },
  { name: "SCARD", syntax: "SCARD key" },
  { name: "SPOP", syntax: "SPOP key [count]" },
  { name: "SRANDMEMBER", syntax: "SRANDMEMBER key [count]" },
  { name: "SMOVE", syntax: "SMOVE source destination member" },
  { name: "SUNION", syntax: "SUNION key [key ...]" },
  { name: "SUNIONSTORE", syntax: "SUNIONSTORE destination key [key ...]" },
  { name: "SINTER", syntax: "SINTER key [key ...]" },
  { name: "SINTERCARD", syntax: "SINTERCARD numkeys key [key ...] [LIMIT limit]" },
  { name: "SINTERSTORE", syntax: "SINTERSTORE destination key [key ...]" },
  { name: "SDIFF", syntax: "SDIFF key [key ...]" },
  { name: "SDIFFSTORE", syntax: "SDIFFSTORE destination key [key ...]" },
  { name: "SSCAN", syntax: "SSCAN key cursor [MATCH pattern] [COUNT count]" },

  // Sorted sets
  { name: "ZADD", syntax: "ZADD key [NX|XX] [GT|LT] [CH] [INCR] score member [score member ...]" },
  { name: "ZREM", syntax: "ZREM key member [member ...]" },
  { name: "ZSCORE", syntax: "ZSCORE key member" },
  { name: "ZMSCORE", syntax: "ZMSCORE key member [member ...]" },
  { name: "ZCARD", syntax: "ZCARD key" },
  { name: "ZCOUNT", syntax: "ZCOUNT key min max" },
  { name: "ZINCRBY", syntax: "ZINCRBY key increment member" },
  { name: "ZRANK", syntax: "ZRANK key member [WITHSCORE]" },
  { name: "ZREVRANK", syntax: "ZREVRANK key member [WITHSCORE]" },
  { name: "ZRANGE", syntax: "ZRANGE key start stop [BYSCORE|BYLEX] [REV] [LIMIT offset count] [WITHSCORES]" },
  { name: "ZREVRANGE", syntax: "ZREVRANGE key start stop [WITHSCORES]" },
  { name: "ZRANGEBYSCORE", syntax: "ZRANGEBYSCORE key min max [WITHSCORES] [LIMIT offset count]" },
  { name: "ZREVRANGEBYSCORE", syntax: "ZREVRANGEBYSCORE key max min [WITHSCORES] [LIMIT offset count]" },
  { name: "ZRANGEBYLEX", syntax: "ZRANGEBYLEX key min max [LIMIT offset count]" },
  { name: "ZRANGESTORE", syntax: "ZRANGESTORE dst src start stop [BYSCORE|BYLEX] [REV] [LIMIT offset count]" },
  { name: "ZREMRANGEBYRANK", syntax: "ZREMRANGEBYRANK key start stop" },
  { name: "ZREMRANGEBYSCORE", syntax: "ZREMRANGEBYSCORE key min max" },
  { name: "ZREMRANGEBYLEX", syntax: "ZREMRANGEBYLEX key min max" },
  { name: "ZPOPMIN", syntax: "ZPOPMIN key [count]" },
  { name: "ZPOPMAX", syntax: "ZPOPMAX key [count]" },
  { name: "ZRANDMEMBER", syntax: "ZRANDMEMBER key [count [WITHSCORES]]" },
  { name: "ZUNION", syntax: "ZUNION numkeys key [key ...] [WEIGHTS ...] [AGGREGATE SUM|MIN|MAX] [WITHSCORES]" },
  { name: "ZUNIONSTORE", syntax: "ZUNIONSTORE destination numkeys key [key ...] [WEIGHTS ...] [AGGREGATE ...]" },
  { name: "ZINTER", syntax: "ZINTER numkeys key [key ...] [WEIGHTS ...] [AGGREGATE ...] [WITHSCORES]" },
  { name: "ZINTERCARD", syntax: "ZINTERCARD numkeys key [key ...] [LIMIT limit]" },
  { name: "ZINTERSTORE", syntax: "ZINTERSTORE destination numkeys key [key ...] [WEIGHTS ...] [AGGREGATE ...]" },
  { name: "ZDIFF", syntax: "ZDIFF numkeys key [key ...] [WITHSCORES]" },
  { name: "ZDIFFSTORE", syntax: "ZDIFFSTORE destination numkeys key [key ...]" },
  { name: "ZSCAN", syntax: "ZSCAN key cursor [MATCH pattern] [COUNT count]" },
  { name: "ZMPOP", syntax: "ZMPOP numkeys key [key ...] MIN|MAX [COUNT count]" },

  // HyperLogLog
  { name: "PFADD", syntax: "PFADD key [element ...]" },
  { name: "PFCOUNT", syntax: "PFCOUNT key [key ...]" },
  { name: "PFMERGE", syntax: "PFMERGE destkey [sourcekey ...]" },

  // Geo
  { name: "GEOADD", syntax: "GEOADD key longitude latitude member [...]" },
  { name: "GEOPOS", syntax: "GEOPOS key member [member ...]" },
  { name: "GEODIST", syntax: "GEODIST key member1 member2 [m|km|ft|mi]" },
  { name: "GEOSEARCH", syntax: "GEOSEARCH key FROMMEMBER member|FROMLONLAT lon lat BYRADIUS r unit|BYBOX w h unit" },

  // Streams
  { name: "XADD", syntax: "XADD key [NOMKSTREAM] [MAXLEN|MINID ...] *|id field value [...]" },
  { name: "XLEN", syntax: "XLEN key" },
  { name: "XRANGE", syntax: "XRANGE key start end [COUNT count]" },
  { name: "XREVRANGE", syntax: "XREVRANGE key end start [COUNT count]" },
  { name: "XREAD", syntax: "XREAD [COUNT count] [BLOCK ms] STREAMS key [key ...] id [id ...]" },
  { name: "XDEL", syntax: "XDEL key id [id ...]" },
  { name: "XTRIM", syntax: "XTRIM key MAXLEN|MINID [=|~] threshold" },
  { name: "XGROUP", syntax: "XGROUP CREATE|SETID|DESTROY|CREATECONSUMER|DELCONSUMER ..." },
  { name: "XREADGROUP", syntax: "XREADGROUP GROUP group consumer [COUNT count] [BLOCK ms] STREAMS key ... id ..." },
  { name: "XACK", syntax: "XACK key group id [id ...]" },
  { name: "XPENDING", syntax: "XPENDING key group [[IDLE min-idle] start end count [consumer]]" },
  { name: "XCLAIM", syntax: "XCLAIM key group consumer min-idle-time id [id ...]" },
  { name: "XAUTOCLAIM", syntax: "XAUTOCLAIM key group consumer min-idle-time start [COUNT count]" },
  { name: "XINFO", syntax: "XINFO STREAM|GROUPS|CONSUMERS key" },

  // Pub/Sub
  { name: "SUBSCRIBE", syntax: "SUBSCRIBE channel [channel ...]" },
  { name: "UNSUBSCRIBE", syntax: "UNSUBSCRIBE [channel ...]" },
  { name: "PSUBSCRIBE", syntax: "PSUBSCRIBE pattern [pattern ...]" },
  { name: "PUNSUBSCRIBE", syntax: "PUNSUBSCRIBE [pattern ...]" },
  { name: "PUBLISH", syntax: "PUBLISH channel message" },
  { name: "PUBSUB", syntax: "PUBSUB CHANNELS|NUMSUB|NUMPAT [argument ...]" },

  // Transactions
  { name: "MULTI", syntax: "MULTI" },
  { name: "EXEC", syntax: "EXEC" },
  { name: "DISCARD", syntax: "DISCARD" },
  { name: "WATCH", syntax: "WATCH key [key ...]" },
  { name: "UNWATCH", syntax: "UNWATCH" },

  // Scripting / functions
  { name: "EVAL", syntax: "EVAL script numkeys [key ...] [arg ...]" },
  { name: "EVALSHA", syntax: "EVALSHA sha1 numkeys [key ...] [arg ...]" },
  { name: "SCRIPT", syntax: "SCRIPT LOAD|EXISTS|FLUSH|KILL ..." },
  { name: "FUNCTION", syntax: "FUNCTION LOAD|DELETE|FLUSH|LIST|DUMP|RESTORE|STATS ..." },
  { name: "FCALL", syntax: "FCALL function numkeys [key ...] [arg ...]" },

  // Connection
  { name: "PING", syntax: "PING [message]" },
  { name: "ECHO", syntax: "ECHO message" },
  { name: "SELECT", syntax: "SELECT index" },
  { name: "SWAPDB", syntax: "SWAPDB index1 index2" },
  { name: "AUTH", syntax: "AUTH [username] password" },
  { name: "HELLO", syntax: "HELLO [protover [AUTH username password] [SETNAME clientname]]" },
  { name: "CLIENT", syntax: "CLIENT LIST|INFO|SETNAME|GETNAME|KILL|PAUSE|UNPAUSE|NO-EVICT ..." },

  // Server / admin
  { name: "INFO", syntax: "INFO [section]" },
  { name: "CONFIG", syntax: "CONFIG GET|SET|REWRITE|RESETSTAT parameter [value]" },
  { name: "COMMAND", syntax: "COMMAND [COUNT|DOCS|INFO|LIST|GETKEYS]" },
  { name: "FLUSHDB", syntax: "FLUSHDB [ASYNC|SYNC]" },
  { name: "FLUSHALL", syntax: "FLUSHALL [ASYNC|SYNC]" },
  { name: "SLOWLOG", syntax: "SLOWLOG GET|LEN|RESET [count]" },
  { name: "LATENCY", syntax: "LATENCY HISTORY|LATEST|RESET|GRAPH|DOCTOR [event]" },
  { name: "MEMORY", syntax: "MEMORY USAGE key|STATS|DOCTOR|PURGE" },
  { name: "LASTSAVE", syntax: "LASTSAVE" },
  { name: "SAVE", syntax: "SAVE" },
  { name: "BGSAVE", syntax: "BGSAVE [SCHEDULE]" },
  { name: "BGREWRITEAOF", syntax: "BGREWRITEAOF" },
  { name: "SHUTDOWN", syntax: "SHUTDOWN [NOSAVE|SAVE] [NOW] [FORCE] [ABORT]" },
  { name: "TIME", syntax: "TIME" },
  { name: "DEBUG", syntax: "DEBUG subcommand [arguments]" },
  { name: "MONITOR", syntax: "MONITOR" },
  { name: "REPLICAOF", syntax: "REPLICAOF host port|NO ONE" },
  { name: "ACL", syntax: "ACL LIST|CAT|GETUSER|SETUSER|DELUSER|WHOAMI ..." },
  { name: "CLUSTER", syntax: "CLUSTER INFO|NODES|SLOTS|SHARDS|KEYSLOT ..." },
  { name: "LOLWUT", syntax: "LOLWUT" },
];

// Commands that take a subcommand as their second token, mapped to that subcommand's options.
export const SUBCOMMANDS: Record<string, string[]> = {
  CONFIG: ["GET", "SET", "REWRITE", "RESETSTAT"],
  CLIENT: [
    "LIST", "INFO", "SETNAME", "GETNAME", "KILL", "PAUSE", "UNPAUSE",
    "NO-EVICT", "NO-TOUCH", "ID", "REPLY", "UNPAUSE",
  ],
  COMMAND: ["COUNT", "DOCS", "INFO", "LIST", "GETKEYS", "GETKEYSANDFLAGS"],
  OBJECT: ["ENCODING", "FREQ", "IDLETIME", "REFCOUNT", "HELP"],
  SCRIPT: ["LOAD", "EXISTS", "FLUSH", "KILL"],
  FUNCTION: ["LOAD", "DELETE", "FLUSH", "LIST", "DUMP", "RESTORE", "STATS", "KILL"],
  XGROUP: ["CREATE", "SETID", "DESTROY", "CREATECONSUMER", "DELCONSUMER"],
  XINFO: ["STREAM", "GROUPS", "CONSUMERS"],
  ACL: ["LIST", "CAT", "GETUSER", "SETUSER", "DELUSER", "WHOAMI", "USERS", "SAVE", "LOAD", "LOG"],
  CLUSTER: ["INFO", "NODES", "SLOTS", "SHARDS", "KEYSLOT", "MYID", "RESET", "FAILOVER"],
  SLOWLOG: ["GET", "LEN", "RESET"],
  LATENCY: ["HISTORY", "LATEST", "RESET", "GRAPH", "DOCTOR"],
  MEMORY: ["USAGE", "STATS", "DOCTOR", "PURGE"],
  PUBSUB: ["CHANNELS", "NUMSUB", "NUMPAT", "SHARDCHANNELS", "SHARDNUMSUB"],
  DEBUG: ["OBJECT", "SLEEP", "JMAP", "SET-ACTIVE-EXPIRE", "STRINGMATCH-LEN", "QUICKLIST-PACKED-THRESHOLD"],
};

export const COMMAND_BY_NAME: Record<string, CommandSpec> = Object.fromEntries(
  REDIS_COMMANDS.map((c) => [c.name, c])
);
